version: '3.9'
services:
  mongo:
    container_name: mongo
    image: mongo:4.4.3
    networks:
      - pritunl
    restart: always
    volumes:
      - ./mongo/db:/data/db
  pritunl:
    container_name: pritunl
    build: .
    image: pritunl
    depends_on:
      - mongo
    networks:
      - pritunl
    ports:
      - "1194:1194/tcp"
      - "443:443"
      - "80:1194/tcp"
    privileged: true
    restart: always
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
networks:
  pritunl:

